# Generated by Django 4.0.6 on 2022-07-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_alter_actor_options_alter_director_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='Aprašymas'),
        ),
    ]
