# Generated by Django 4.0.6 on 2022-07-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0006_remove_performanceinstance_viewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceinstance',
            name='ticket',
            field=models.IntegerField(default=0, verbose_name='Bilietas'),
        ),
    ]
