# Generated by Django 4.0.6 on 2022-07-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0008_alter_performanceinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='director',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='director',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='director',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='enter the genre of the performance', max_length=200, verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='actor',
            field=models.ManyToManyField(help_text='choose the actors of the play', to='theater.actor'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='author',
            field=models.CharField(max_length=200, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='summary',
            field=models.TextField(max_length=500, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='performanceinstance',
            name='performance_date',
            field=models.DateField(blank=True, null=True, verbose_name='performance_date'),
        ),
        migrations.AlterField(
            model_name='performanceinstance',
            name='ticket',
            field=models.IntegerField(default=0, verbose_name='ticket'),
        ),
    ]
