# Generated by Django 4.0.6 on 2022-07-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='user_profile/img/default.png', upload_to='user_profile/img/', verbose_name='picture'),
        ),
    ]
